apiVersion: apps/v1
kind: Deployment
metadata:
  name: dividingway
  namespace: dividingway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dividingway
  template:
    metadata:
      labels:
        app: dividingway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: github
      containers:
      - name: dividingway
        image: ghcr.io/veraticus/dividingway:sha-4897862
        envFrom:
        - secretRef:
            name: env
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
