---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: open-telemetry
spec:
  interval: 1m0s
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: collector-daemonset
  namespace: open-telemetry
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.102.1
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
  values:
    image:
      repository: otel/opentelemetry-collector-k8s

    mode: daemonset

    clusterRole:
      create: true

    extraEnvs:
      - name: HONEYCOMB_API_KEY
        valueFrom:
          secretKeyRef:
            name: env
            key: HONEYCOMB_API_KEY
      - name: NODE_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.hostIP

    extraVolumeMounts:
      - name: hostfs
        mountPath: /hostfs
        readOnly: true
        mountPropagation: HostToContainer
    extraVolumes:
      - name: hostfs
        hostPath:
          path: /

    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: false
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
        extractAllPodAnnotations: true
      kubeletMetrics:
        enabled: false
      hostMetrics:
        enabled: false

    config:
      receivers:
        jaeger: null
        zipkin: null

      exporters:
        otlp/honeycomb-traces:
          endpoint: "api.honeycomb.io:443"
          headers:
            "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
        otlp/honeycomb-metrics:
          endpoint: "api.honeycomb.io:443"
          headers:
            "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
            "x-honeycomb-dataset": "metrics"
        otlp/honeycomb-logs:
          endpoint: "api.honeycomb.io:443"
          headers:
            "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
            "x-honeycomb-dataset": "logs"

      extensions:
        health_check: {}

      processors:
        batch: {}
        memory_limiter:
          check_interval: 5s
          limit_percentage: 80
          spike_limit_percentage: 25

      service:
        extensions: [ health_check ]
        pipelines:
          traces:
            receivers: [ otlp ]
            processors: [ memory_limiter, batch ]
            exporters: [ otlp/honeycomb-traces ]
          metrics:
            receivers: [ otlp ]
            processors: [ memory_limiter, batch ]
            exporters: [ otlp/honeycomb-metrics ]
          logs:
            receivers: [ otlp ]
            processors: [ memory_limiter, batch ]
            exporters: [ otlp/honeycomb-logs ]
    ports:
      jaeger-compact:
        enabled: false
      jaeger-thrift:
        enabled: false
      jaeger-grpc:
        enabled: false
      zipkin:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 2000Mi
