---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: open-telemetry
spec:
  encryptedData:
    HONEYCOMB_API_KEY: AgBAVn2+r3K45EkN+ysWccl0SeFPpU64ijd8SAf5/+1hdTW7V5JHOyhA2EW0F57iY5F450i6E6P6158K1wbymJslllV4h4rfZcXgujTfbb3yvobvrNb0x5i8ljG7RGEut98mt3Z3SbwASP99jmNGAK/RqD9sOck78JE1lsjOxY9ovkgO+8mPdCKdUBt2THTBaSNbONmfXY2X/7edEeXGg1qi5zmtwyFGZL1F+blRwPFsDC2nU0ZnplYQn43ImCnYSwrfWiPD9eCJNWKjLj71Yso5jcEi25LOJnFzAldNaz+aeRCehr4A8IALc9vLorIZO4OIIg8Z5oV1xCH6DXLDYZsFLZg/Du93YOQj1SXq40bBN45/jq/1dcLpViyxQdzORiNJbfkV9qw9rKn1RBxhjJiWqaVaYoHNnREMoyhHGupA8cyOcA0T5LXvMX6cboFWnA5he1DmOCuN9sSoDwtrNlWYUy946x/nJvYbsEFijL8Xov6AyU//5S/ZTcRPI6pSMVqYVWHLf6n82N1/eZdmbuqW0tsZ7XxxRDEbYyxsNH8v4sqyTGz4I2xqWAIGRwpnILXttgEvU3fCw4wyQnJUasfNlFOAJBZ+On+yZMMLIjRDAAIIyB54xDMVqBlwiIWGctW5kNqc8AXEwOnZ2uakxmDD9VEgO5ZPbXrthS8sbmWjg3EHALMu75k9vjkMYTqt3v4sjc6a7dULQ+UNEU7UePj/8Entdm3QfCLKjYYsMrmtsHRUqSRgLc/cBV+QPD0Wl+Z8hJowi7waWDyqDByNI4B2
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: open-telemetry
