apiVersion: apps/v1
kind: Deployment
metadata:
  name: moddingway
  namespace: moddingway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moddingway
      component: app
  template:
    metadata:
      labels:
        app: moddingway
        component: app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: github
      containers:
      - name: moddingway
        image: ghcr.io/naurffxiv/moddingway:app-16e2742
        envFrom:
        - secretRef:
            name: env
        env:
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
