---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: moddingway
spec:
  encryptedData:
    DISCORD_TOKEN: AgB/NMbchjpT+SjrvlW4XRar+GWxkvzryozQiQe1SnvfKWZHks8DHIXxAq4OoidgJM1YRI7+qnVWH/kNanS4R1r5UR2L1pVr2/Qk04MuYoK5SMffSDPodrji0OX6OjHfcddw0Gesye55c9kRU/zRSMLs24rj/SXmNBUazEWX1fbbnPAsIrVmiy4c1VFbtqbeA6nnwjJ9g1ikt1GKKZgDnzYaX0PzotsKiR6JCcc/YSNBTpuQQ1HCLejP907zVrFrn8hNkN+DiY2WkfUA/OKAIQGvWTRsSy63zYMR7MtAShB+AevJaCgg92mnFzTlJlSnlECT4uEk0FdXeSeJtWwZQOwZBB7c233bHjib2zgWMPsDbZ7YnxKsRa0DsFdpcOLDdPHEOn6mTlQDTVCgc10YZqSILUgkrfQcA5LfK5o3dMDzm7Bd9d+/TOAxa8bnG0F/lVrX439eZU5npepxqqO7ux/m2DI9ueWQm4A0AatX8xn4qG3sjLquklEFIUMOt8X5eV5maRbg1FDfpy1dgD+wCeNEv7wNP7+L7huWAkkKMnr6p3+nPotle/8M8d2E1M4aew0XLuP9L9SRWQlhy3quz5k7SDHiR+fqwvQ9vyrJbM7r3IXb4SDfnf+UcX6FzngBhVTNISvD3VYkTIV/+riC/kCiRw0RlAw9Wk763yFjlDrV3DhsUas217Ms96GjgCoV7zFBSYR51r86WxSFyLMteekn87/5M6WmEyaGuUVCPVAaOwoe3Hyrlj/GWzUQd7sJJRa1s6cUP3XAuHWt8FoQPb6pvXC2hHXMqtk=
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: moddingway
