---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    DISCORD_TOKEN: AgAvZB8BO69LvJSlbnmwcV6OcNggtgNzg1jmy1lP9P4Lx0+D1KbWM7i/SePduCq+xB6QTcFmcYf9h9r9BNfuNfF9QPzTwmm0cu1gvHvowk8v8pdDK8RUB2X0riS1a5HtLaq26GVk3DzjRIt9PQ9n2oqAm223FQtiZylLeLozSRMBzsnEkeLT0omMFT8ObPkESQg06P8FgsLIq6FlEkVt225rziGbSRVfK+EZIvPLYfQbs6NNG6savKVgZdDCEaVb4sOkr5LaP0r9SJ3if57xAUblcE4l5r1yn1mOL1aSL3IFB2c5d9AS/Da/l7fFcw65BtVvcLPzaVRqLVAboNWudvlapMTac0X2so2FtKGk1Xyj4wedDHbxgBTvxZ2zJvTnhzGIjAPptYb+AiMcDTiXC9cUzuZDOBCyDiJfV6bCmOeTlTzFQyWUaWNElN/rhIBX7LJnNJBWjvxFzWm5Kz+j5ybbrI1Ed0We4FqJA+QmhShVayk9FS5ekf9WlQPK88U0z21Aduv8MY5NuTGkcugzu4xs2NBPyRfCMY3jDQb6D3713iDVcpoy9TKIb6HzN1kpDafoMzfMdcEqcF0PPedeHy7mgNfjkMz3iMIFV7MSMaiGFuKsRR20z/u7PSPsAsOilZWElINDVc4XA+yoArWQMmv6QDPqXkgHpGPUFMx0Di/oGPvwR+D7snPoC53bfRtRq2+cvFJPKxO9DCUEuD29lj5NlkMqZGm9nhH/oPBR7fa9GJY28csQL7Jaolanos72RhQikvJvgQ/SFZZYPhqwCX0QWUNIG176Jw==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
